#!/usr/bin/env python3
"""Plot flight data from CSV files generated by plot_path_mpc.py."""

import sys
import os
import glob
import csv
import matplotlib.pyplot as plt
import numpy as np


def load_csv(csv_path):
    """Load CSV into a dict of numpy arrays."""
    with open(csv_path, 'r') as f:
        reader = csv.reader(f)
        headers = next(reader)
        rows = [row for row in reader]
    data = {}
    for i, h in enumerate(headers):
        data[h] = np.array([float(row[i]) for row in rows])
    return data


def parse_env_tag(fname):
    """Extract environment tag from filename like flight_..._MODE_wind.csv"""
    base = fname.replace('.csv', '').replace('.png', '')
    if base.endswith('_wind'):
        return 'wind'
    elif base.endswith('_nowind'):
        return 'nowind'
    return 'unknown'


def plot_flight(csv_path):
    d = load_csv(csv_path)
    t = d['time_s']
    fname = os.path.basename(csv_path)
    env_tag = parse_env_tag(fname)
    env_label = {'wind': 'With Wind (4 m/s, -Y)', 'nowind': 'No Wind', 'unknown': ''}[env_tag]

    fig, axes = plt.subplots(3, 2, figsize=(14, 10))
    title = f'Flight Data: {fname}'
    if env_label:
        title += f'  [{env_label}]'
    fig.suptitle(title, fontsize=13)

    # --- 1. Position X/Y/Z vs Setpoint ---
    ax = axes[0, 0]
    ax.plot(t, d['curr_x'], 'b-', label='curr_x')
    ax.plot(t, d['tgt_x'], 'b--', alpha=0.5, label='tgt_x')
    ax.plot(t, d['curr_y'], 'r-', label='curr_y')
    ax.plot(t, d['tgt_y'], 'r--', alpha=0.5, label='tgt_y')
    ax.plot(t, d['curr_z'], 'g-', label='curr_z')
    ax.plot(t, d['tgt_z'], 'g--', alpha=0.5, label='tgt_z')
    ax.set_ylabel('Position (m)')
    ax.set_title('Position vs Setpoint')
    ax.legend(fontsize=7, ncol=2)
    ax.grid(True, alpha=0.3)

    # --- 2. Position Error ---
    ax = axes[0, 1]
    err_x = d['curr_x'] - d['tgt_x']
    err_y = d['curr_y'] - d['tgt_y']
    err_z = d['curr_z'] - d['tgt_z']
    err_total = np.sqrt(err_x**2 + err_y**2 + err_z**2)
    ax.plot(t, err_x, 'b-', label='err_x')
    ax.plot(t, err_y, 'r-', label='err_y')
    ax.plot(t, err_z, 'g-', label='err_z')
    ax.plot(t, err_total, 'k--', linewidth=1.5, label='||err||')
    ax.set_ylabel('Error (m)')
    ax.set_title('Position Error')
    ax.legend(fontsize=7)
    ax.grid(True, alpha=0.3)

    # --- 3. Velocity ---
    ax = axes[1, 0]
    ax.plot(t, d['vel_x'], 'b-', label='vel_x')
    ax.plot(t, d['vel_y'], 'r-', label='vel_y')
    ax.plot(t, d['vel_z'], 'g-', label='vel_z')
    speed = np.sqrt(d['vel_x']**2 + d['vel_y']**2 + d['vel_z']**2)
    ax.plot(t, speed, 'k--', linewidth=1.5, label='speed')
    ax.set_ylabel('Velocity (m/s)')
    ax.set_title('Velocity')
    ax.legend(fontsize=7)
    ax.grid(True, alpha=0.3)

    # --- 4. Roll / Pitch / Yaw ---
    ax = axes[1, 1]
    ax.plot(t, np.degrees(d['roll_rad']), 'b-', label='roll')
    ax.plot(t, np.degrees(d['pitch_rad']), 'r-', label='pitch')
    ax.plot(t, np.degrees(d['yaw_rad']), 'g-', label='yaw')
    ax.set_ylabel('Angle (deg)')
    ax.set_title('Attitude (Roll / Pitch / Yaw)')
    ax.legend(fontsize=7)
    ax.grid(True, alpha=0.3)

    # --- 5. 3D Trajectory ---
    ax = fig.add_subplot(3, 2, 5, projection='3d')
    axes[2, 0].set_visible(False)
    ax.plot(d['curr_x'], d['curr_y'], d['curr_z'], 'b-', label='Actual')
    ax.plot(d['tgt_x'], d['tgt_y'], d['tgt_z'], 'g--', alpha=0.6, label='Target')
    ax.scatter(d['curr_x'][0], d['curr_y'][0], d['curr_z'][0],
               color='blue', marker='o', s=60, label='Start')
    ax.scatter(d['tgt_x'][-1], d['tgt_y'][-1], d['tgt_z'][-1],
               color='green', marker='x', s=100, label='Goal')
    ax.set_xlabel('X'); ax.set_ylabel('Y'); ax.set_zlabel('Z')
    ax.set_title('3D Path')
    ax.legend(fontsize=7)

    # --- 6. Summary stats ---
    ax = axes[2, 1]
    ax.axis('off')
    settle_idx = np.where(err_total < 0.15)[0]
    settle_time = f"{t[settle_idx[0]]:.2f}s" if len(settle_idx) > 0 else "N/A"

    stats_text = (
        f"Environment:  {env_label or 'N/A'}\n"
        f"Settle time (||err|| < 0.15m):  {settle_time}\n"
        f"Final error:  {err_total[-1]:.4f} m\n"
        f"Max |err_x|:  {np.abs(err_x).max():.4f} m\n"
        f"Max |err_y|:  {np.abs(err_y).max():.4f} m\n"
        f"Max |err_z|:  {np.abs(err_z).max():.4f} m\n"
        f"Max speed:  {speed.max():.3f} m/s\n"
        f"Max |roll|:  {np.degrees(np.abs(d['roll_rad']).max()):.2f} deg\n"
        f"Max |pitch|:  {np.degrees(np.abs(d['pitch_rad']).max()):.2f} deg\n"
        f"Duration:  {t[-1]:.2f} s\n"
        f"Samples:  {len(t)}"
    )
    ax.text(0.05, 0.95, stats_text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', fontfamily='monospace',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    ax.set_title('Summary')

    plt.tight_layout()
    png_path = csv_path.replace('.csv', '.png')
    plt.savefig(png_path, dpi=150)
    print(f"Saved plot: {png_path}")
    plt.show()


def main():
    docs_dir = os.path.dirname(os.path.abspath(__file__))

    if len(sys.argv) > 1:
        csv_files = sys.argv[1:]
    else:
        csv_files = sorted(glob.glob(os.path.join(docs_dir, 'flight_*.csv')))
        if not csv_files:
            print("No flight CSV files found in docs/")
            print(f"Usage: python3 {sys.argv[0]} [path_to_csv ...]")
            return
        csv_files = [csv_files[-1]]
        print(f"No file specified, plotting latest: {os.path.basename(csv_files[0])}")

    for csv_path in csv_files:
        if not os.path.isfile(csv_path):
            print(f"File not found: {csv_path}")
            continue
        plot_flight(csv_path)


if __name__ == '__main__':
    main()
